services:
  backend:
    build: .
    container_name: nusci-backend
    ports:
      - 9999:9999
  app:
    build: .
    container_name: nusci-frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
